Repository precice/openfoam-adapter, pull requests merged in 2024-03, with the labels that each got.

#321 Add pre-commit for liniting docs
  .github/workflows/check-markdown.yml
  .github/workflows/check-style.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
Labels: dev

#322 Remove unnecessary `timestepPrecice_`
  Adapter.C
  Adapter.H
Labels: enhancement

#309 Added a test workflow
  .github/workflows/system-tests.yaml
  CONTRIBUTING.md
Labels: trigger-system-tests
